### PR TITLE
Adding ansible and vagrant

### PR DESCRIPTION
**Pull request by solojavier**
Adding ansible and vagrant to have a similar setup as in tdd-js

### CODE REVIEW

**Comment by solojavier** [comment]
@sawyer-effect/developers 

Let me know if there is any feedback before we merge this, also if anyone could test if it works in your local machine that would be great

**Comment by hackergil** [comment]
After installing vagrant, virtualbox and ansible I was able to successfully start the VM and provision via ansible

**Comment by solojavier** [comment]
@hackergil were you able to run the command to run the tests and see the result too?

**Comment by hackergil** [comment]
I just did. All good.

**Comment by solojavier** [comment]
Thanks!

**Pull request merged**
